name: 'イメージビルド'
description: 'Dockerイメージをつくります、ついでにpushもします'

inputs:
    REGISTRY:
      description: 'コンテナレジストリ'
      required: true
      default: 'ghcr.io'
    IMAGE_NAME:
      description: 'イメージ名'
      required: true
      default: 'linux'
    REPO_USER:
      desctiption: 'リポジトリアクセスユーザー名'
      required: true
    REPO_TOKEN:
      description: 'リポジトリトークン(パスワード)'
      required: true
    TAGS:
      description: 'タグ'
      required: true

runs:
    using: 'composite'
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      # コンテナレジストリ荷ログインする
      uses: docker/login-action@v3
      with:
        registry: ${{ input.REGISTRY }}
        username: ${{ input.REPO_USER }}
        password: ${{ input.REPO_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      # リポジトリからメタデータを取得する
      id: meta
      uses: docker/metadata-action@v4
      with:
          images: ${{ input.IMAGE_NAME }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: src
        push: true
        tags: |
          ${{ input.TAGS }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          PASSWORD=penguin
        platforms: linux/amd64,linux/arm64
        provenance: false
